name: Go Report Card

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  generate_report_card:
    runs-on: ubuntu-latest
    steps:
      - name: Go report card
        uses: creekorful/goreportcard-action@v1.0
